# Generated by Django 4.1.7 on 2023-03-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_parent_category_alter_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
