# Generated by Django 4.1.7 on 2023-03-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_logolayon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logolayon',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Видео'),
        ),
    ]
