# Generated by Django 4.1.7 on 2023-03-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_logolayon_video'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logolayon',
            table='shop_logo_lay_on',
        ),
    ]
