# Generated by Django 4.1.7 on 2023-03-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_logolayon_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('type', models.CharField(choices=[('call-order', 'Звонок на заказ'), ('dealer', 'Дилер'), ('provider', 'Поставщик')], default='call-order', max_length=10, verbose_name='Тип клиента')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
        ),
    ]
