# Generated by Django 4.1.7 on 2023-03-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ("-id",),
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.AlterField(
            model_name="logolayon",
            name="video",
            field=models.FileField(
                upload_to="logo-lay-ons/videos/", verbose_name="Видео"
            ),
        ),
    ]
