# Generated by Django 4.1.7 on 2023-03-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_contact_options_alter_logolayon_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_contacts', to='shop.product', verbose_name='Продукт'),
        ),
    ]
