# Generated by Django 4.1.7 on 2023-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_contact_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('call-order', 'Звонок на заказ'), ('product-order', 'Заказ продукта'), ('dealer', 'Дилер'), ('provider', 'Поставщик')], default='call-order', max_length=20, verbose_name='Тип клиента'),
        ),
    ]
